version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REBUILD_DEPS: "true"  # Force dependency reinstall
    ports:
      - "5000:5000"
    volumes:
      # Mount specific directories instead of replacing the entire application
      - ./pdfMergerWebsite/static:/app/static
      - ./pdfMergerWebsite/templates:/app/templates
      - ./pdfMergerWebsite/frontend:/app/frontend
      # Add a volume for persistent PDF storage
      - pdf_data:/app/data
    environment:
      - FLASK_ENV=development
      - PDF_EXPIRY_SECONDS=86400  # Extend to 24 hours for better debugging
      - PERSISTENCE_ENABLED=true  # Enable persistence by default
      - PERSISTENCE_INTERVAL=15   # Save more frequently (every 15 seconds)
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  pdf_data:  # Define a named volume for persistent storage